// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/8/2025, 5:17:38 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/kinyano/Desktop/savr/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/savr/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/savr/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/savr/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/savr/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/savr/plugins/**/*.{js,ts,mjs}","/Users/kinyano/Desktop/savr/composables/**/*.{js,ts,mjs}","/Users/kinyano/Desktop/savr/utils/**/*.{js,ts,mjs}","/Users/kinyano/Desktop/savr/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/savr/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/savr/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;